# ??????
spring:
  application:
    name: ????????
  # ?? dev ??
  profiles:
    active: local
  # ?? swagger3
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  # session ??
  session:
    # todo ????????? session????? Redis?
    store-type: redis
    # 30 ???
    timeout: 2592000
  # ?????
  # todo ?????
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/arona_shop?serverTimezone=Asia/Shanghai
    username: root
    password: 
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  # Redis ??
  # todo ????????????
  redis:
    database: 1
    host: localhost
    port: 6379
  # ????
  servlet:
    multipart:
      # ????
      max-file-size: 10MB
server:
  address: 0.0.0.0
  port: 8101
  servlet:
    context-path: /api
    # cookie 30 ???
    session:
      cookie:
        max-age: 2592000
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDelete # ????????????
      logic-delete-value: 1 # ?????????? 1?
      logic-not-delete-value: 0 # ?????????? 0?
# ???
tencent:
  cos:
    accessKey: xxx
    secretKey: xxx
    region: xxx
    bucket: xxx
#springdoc????
springdoc:
  swagger-ui:
    #???swagger?????????http?127.0.0.1:8080/swagger-ui.html???????swagger??
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs    #swagger??????
    enabled: true   #????????
  group-configs:
    - group: 'com.software_system_development.arona_mysterious_shop_backend'
      paths-to-match: '/**'
      packages-to-scan: com.software_system_development.arona_mysterious_shop_backend    #??????:?????????
#knife4j???? ?????
knife4j:
  enable: true    #??knife4j?????@EnableKnife4j??
  setting:
    language: zh_cn   #??